import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import test from 'node:test';
test('identity migration enforces verified claiming, historical snapshots and private responses', async () => {
 const db = new PGlite();
 await db.exec(`create role anon; create role authenticated; create schema auth;
 create table auth.users(id uuid primary key, email text, phone text, email_confirmed_at timestamptz, phone_confirmed_at timestamptz, is_anonymous boolean default false);
 create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub', true),'')::uuid $$;
 grant usage on schema public,auth to authenticated,anon; grant execute on function auth.uid() to authenticated,anon;`);
 await db.exec(await readFile(new URL('../../supabase/migrations/202609300001_identity_foundation.sql', import.meta.url),'utf8'));
 const org='10000000-0000-0000-0000-000000000001', guest='10000000-0000-0000-0000-000000000002', other='10000000-0000-0000-0000-000000000003', phone='10000000-0000-0000-0000-000000000004';
 const decision='20000000-0000-0000-0000-000000000001', different='20000000-0000-0000-0000-000000000002', participant='30000000-0000-0000-0000-000000000001', historical='30000000-0000-0000-0000-000000000002', sms='30000000-0000-0000-0000-000000000003';
 await db.exec(`insert into auth.users(id,email,email_confirmed_at) values ('${org}','org@test.com',now()),('${guest}','guest@test.com',null),('${other}','other@test.com',now()); insert into auth.users(id,phone,phone_confirmed_at) values ('${phone}','14155551234',now());`);
 const as = async id => {await db.exec(`reset role; select set_config('request.jwt.claim.sub','${id}',false); set role authenticated;`);};
 await as(org);
 await db.exec(`insert into public.profiles(id,first_name,last_name,display_name) values ('${org}','Organizer','One',''); insert into public.decisions(id,organizer_id,title) values ('${decision}','${org}','Test'),('${different}','${org}','Other'); insert into public.decision_participants(id,decision_id,first_name,invited_email) values ('${participant}','${decision}','Invited snapshot','guest@test.com'),('${historical}','${different}','Historical','guest@test.com'); insert into public.decision_participants(id,decision_id,first_name,invited_phone) values ('${sms}','${decision}','Phone','+14155551234');`);
 await assert.rejects(db.exec(`insert into public.decision_participants(decision_id,first_name) values ('${decision}','No contact')`));
 await as(guest);
 await assert.rejects(db.exec(`insert into public.profiles(id,first_name,last_name) values ('${guest}','Guest','Two')`));
 assert.equal((await db.query(`select * from public.invite_preview('${participant}')`)).rows.length,0);
 await assert.rejects(db.exec(`select public.claim_participant('${participant}')`));
 await db.exec(`reset role; update auth.users set email_confirmed_at=now() where id='${guest}';`);
 await as(guest);
 assert.equal((await db.query(`select * from public.invite_preview('${participant}')`)).rows[0].first_name,'Invited snapshot');
 await assert.rejects(db.exec(`insert into public.profiles(id,first_name,last_name) values ('${guest}','Guest',' ')`));
 await db.exec(`insert into public.profiles(id,first_name,last_name) values ('${guest}','Guest','Two'); select public.claim_participant('${participant}'); select public.claim_participant('${participant}'); update public.profiles set first_name='Preferred',display_name='Nickname' where id='${guest}';`);
 assert.equal((await db.query(`select first_name from public.decision_participants where id='${participant}'`)).rows[0].first_name,'Invited snapshot');
 assert.equal((await db.query(`select display_name from public.participant_labels('${decision}')`)).rows[0].display_name,'Nickname');
 await assert.rejects(db.exec(`update public.decision_participants set user_id='${other}' where id='${participant}'`));
 await assert.rejects(db.exec(`insert into public.perspectives(decision_id,participant_id,body) values ('${different}','${participant}','Cross decision')`));
 await db.exec(`insert into public.perspectives(decision_id,participant_id,body) values ('${decision}','${participant}','Private')`);
 assert.equal((await db.query('select * from public.perspectives')).rows.length,0);
 await assert.rejects(db.exec(`insert into public.perspectives(decision_id,participant_id,body) values ('${decision}','${participant}','Duplicate')`));
 await as(other);
 await db.exec(`insert into public.profiles(id,first_name,last_name) values ('${other}','Other','Three')`);
 await assert.rejects(db.exec(`select public.claim_participant('${historical}')`));
 assert.equal((await db.query('select * from public.decisions')).rows.length,0);
 assert.equal((await db.query('select * from public.perspectives')).rows.length,0);
 await as(phone);
 await db.exec(`insert into public.profiles(id,first_name,last_name) values ('${phone}','Phone','Four'); select public.claim_participant('${sms}');`);
 assert.equal((await db.query('select * from public.perspectives')).rows.length,0);
 await as(org);
 assert.equal((await db.query('select * from public.perspectives')).rows.length,1);
 assert.equal((await db.query(`select user_id from public.decision_participants where id='${historical}'`)).rows[0].user_id,null);
 await db.exec(`reset role; set role anon;`);
 await assert.rejects(db.query('select * from public.perspectives'));
 await assert.rejects(db.query(`select public.claim_participant('${historical}')`));
 await db.close();
});
